### ISSUE TITLE
Понятные названия

### ISSUE THREAD

**Issue by YegorMan** [Ni1py/Practice#1]
https://github.com/Ni1py/Practice/blob/56a7572f0210782f6d8cfeea7f7a90ff13f2510d/Calculator/Calculator/Program.cs#L19

Не нужно бояться написать длинное название.
Главное - чтобы оно было понятным.
А сейчас оно не очень понятное - это слово ничего не обозначает и не существует в природе :)

**Comment by Ni1py** [comment]
Вы про переменную «calcul»?

Пн, 5 апр. 2021 г. в 11:15, Egor Potekhin ***@***.***>:

**Comment by YegorMan** [comment]
Исправишь название? Чтобы тикет можно было закрыть.

**Comment by Ni1py** [comment]
Да, вот в 5 часов на паре по английскому займусь всеми задачами, а то
времени не было

Чт, 8 апр. 2021 г. в 14:10, Egor Potekhin ***@***.***>:

**Comment by Ni1py** [comment]
https://github.com/Ni1py/Practice/commit/a14e5c14fc6f6ebe5a549453be904497fc2c3dfd

**Comment by YegorMan** [comment]
Локальные переменные необходимо называть с маленькой буквы

**Comment by Ni1py** [comment]
А как тогда слова отделять? Camel case'ом? Как-то так calculationResult?

**Comment by Ni1py** [comment]
Переделал на Camel case 
https://github.com/Ni1py/Practice/commit/78c9ab27c58d22953c3398ffcca602e72910e7b3

**Comment by YegorMan** [comment]
Да, все верно
