### ISSUE TITLE
Должно быть TeacherName

### ISSUE THREAD

**Issue by algolGuru** [Ni1py/Practice#4]
https://github.com/Ni1py/Practice/blob/56a7572f0210782f6d8cfeea7f7a90ff13f2510d/University/University/ISubject.cs#L11

По правилам английского языка переменная должна называться TeacherName

**Comment by Ni1py** [comment]
https://github.com/Ni1py/Practice/commit/78674bcf0c861d8ad2a17e57269cfc382deef691
