### ISSUE TITLE
Функция читается тяжело

### ISSUE THREAD

**Issue by algolGuru** [Ni1py/Practice#5]
https://github.com/Ni1py/Practice/blob/56a7572f0210782f6d8cfeea7f7a90ff13f2510d/University/University/Program.cs#L7

Надо 
1) разделить код на функции
2) Логические блоки отделять пустыми строками

**Comment by Ni1py** [comment]
Пока закрыл только 1 пункт(https://github.com/Ni1py/Practice/commit/c41aff2fe276427605834ef233405b36fabc4926), над вторым надо подумать еще, так как не пойму, как основной код разделить на функции

**Comment by algolGuru** [comment]
Да, конечно можно
Во втором пункте говорится о том, что ваш код решает какую то задачу, по каким то логическим шагам и было бы неплохо в коде такие логические шаги отделять друг от друга пустыми строками

**Comment by algolGuru** [comment]
Но решение с функциями тоже имеет место быть

**Comment by Ni1py** [comment]
А функции называть только глаголами в повелительном наклонении или же можно к ним добавлять что-то? Например, PrintStudentAndSubject?

**Comment by andrey-ilyin** [comment]
Да, добавлять можно. Название PrintStudentAndSubject достаточно информативно.

**Comment by Ni1py** [comment]
Спасибо

**Comment by Ni1py** [comment]
Изменил 1 пункт и сделал 2(https://github.com/Ni1py/Practice/commit/577983bc3d6dec4f3d7849e87ef09670bdafe9a9)

**Comment by Ni1py** [comment]
А, забыл еще в commit дописать, что изменил название переменной c "exam" на "Exam", так как она стала глобальной, ну и соответственно изменил модификатор доступа с "private" на "public"
