### ISSUE TITLE
теперь название функции это существительное

### ISSUE THREAD

**Issue by algolGuru** [Ni1py/Practice#6]
https://github.com/Ni1py/Practice/blob/c41aff2fe276427605834ef233405b36fabc4926/University/University/Grant.cs#L28

**Comment by algolGuru** [comment]
должен быть глагол в повелительном

**Comment by Ni1py** [comment]
Изменил https://github.com/Ni1py/Practice/commit/d53f71adb4b264fd243ac7c54d37b4bcad057c90
Я просто в переводчик ввел "финансировать", он выдал "finance"

**Comment by Ni1py** [comment]
Еще доработал название метода, так как мне сказали, что можно добавлять еще части речи помимо глаголов(https://github.com/Ni1py/Practice/commit/c4081cd75ca4bf1aa31d4a407e8f2883dea42b1a)
