### ISSUE TITLE
Зачем это?

### ISSUE THREAD

**Issue by algolGuru** [Ni1py/Practice#7]
https://github.com/Ni1py/Practice/blob/1be9c8dbe6bb05a978abe8cd67a9cb4e7ccbe65f/StatisticsSQL/StatisticsSQL/Program.cs#L21

**Comment by Ni1py** [comment]
Это я заморочился над красивым выводом. Данной строчкой я добавляю дополнительную табуляцию перед полем NumberOfProducts для 2 и 3 записи, так как в 1 записи длинное имя, поэтому нужна дополнительная табуляция только для 2 и 3 записей, чтобы столбики были ровными.
