### ISSUE TITLE
Вроде как ненужные юзинги

### ISSUE THREAD

**Issue by algolGuru** [Ni1py/Practice#8]
https://github.com/Ni1py/Practice/blob/1be9c8dbe6bb05a978abe8cd67a9cb4e7ccbe65f/StatisticsSQL/StatisticsSQL/Program.cs#L1

**Comment by Ni1py** [comment]
Ненужные юзинги и вправду были, извиняюсь. Но это не "using System" в основной программе. Удалил "using System.Data". В классе Statistics удалил "using System, using System.Collections.Generic, using System.Text"(https://github.com/Ni1py/Practice/commit/fec4ce33ced86e59dae87fe677e3651ee662d884)
